# src/backend/Dockerfile.dev
FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src/backend

# Install dependencies
RUN apt-get update && apt-get install -y \
    tzdata \
    krb5-user \
    bash \
    curl \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 5000

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://0.0.0.0:5000
ENV DOTNET_USE_POLLING_FILE_WATCHER=1
ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true

# Restore NuGet packages
RUN dotnet restore ./Backend.csproj

# Run with hot reload
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5000"]